# Generated by Django 3.0.3 on 2020-03-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fbpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page', models.CharField(blank=True, max_length=20, null=True, verbose_name='Facebookページ名')),
                ('good_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='いいね数')),
                ('category_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name_plural': 'Fbpage',
            },
        ),
    ]
