# Generated by Django 3.0.3 on 2020-03-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbpage',
            name='id_numbers',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='id'),
        ),
    ]
