# Generated by Django 3.0.3 on 2020-03-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_fbpage_id_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbpage',
            old_name='id_numbers',
            new_name='id_number',
        ),
    ]
