# Generated by Django 3.0.3 on 2020-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200319_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbpage',
            name='good_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='いいね数'),
        ),
    ]
