# Generated by Django 3.0.3 on 2020-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
