# Generated by Django 3.0.3 on 2020-03-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200324_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Document'},
        ),
    ]
