# Generated by Django 3.0.3 on 2020-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20200324_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='テキスト'),
        ),
    ]
