# Generated by Django 3.0.3 on 2020-03-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20200324_0310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Fbdate',
        ),
        migrations.AlterModelOptions(
            name='fbdate',
            options={'verbose_name_plural': 'Fbdate'},
        ),
    ]
