# Generated by Django 3.0.3 on 2020-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_fbdate_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbdate',
            name='k_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='k_id'),
        ),
    ]
