# Generated by Django 3.0.3 on 2020-03-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_fbdate_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbdate',
            old_name='k_number',
            new_name='k_id',
        ),
    ]
