# Generated by Django 3.0.3 on 2020-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20200328_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbdate',
            name='day',
            field=models.TextField(blank=True, null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='fbdate',
            name='id_number',
            field=models.TextField(blank=True, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='fbdate',
            name='k_id',
            field=models.TextField(blank=True, null=True, verbose_name='k_id'),
        ),
    ]
